"""Data quality status constants."""

from __future__ import annotations


class DataQualityStatus:
    OK = "OK"
    NO_PRICE = "NO_PRICE"
    NO_VOLUME = "NO_VOLUME"
    NO_ORDERBOOK = "NO_ORDERBOOK"
    NO_ITEM_NAMEID = "NO_ITEM_NAMEID"
    LOW_LIQUIDITY = "LOW_LIQUIDITY"
    FAKE_SPREAD = "FAKE_SPREAD"
    HIGH_RISK = "HIGH_RISK"
    EXCLUDED_APP = "EXCLUDED_APP"
    PARSING_ERROR = "PARSING_ERROR"
    HIGH_PRICE_LOW_VOLUME_WATCHLIST = "HIGH_PRICE_LOW_VOLUME_WATCHLIST"
    PENDING = "PENDING"

    VALID_FOR_CONCLUSIONS = frozenset({OK, HIGH_PRICE_LOW_VOLUME_WATCHLIST})
